// ============================================================
// CampusOS — CSJMU Campus Data
// All campus locations, amenities, routes, and timetable data
// ============================================================

const CAMPUS_CENTER = [26.4499, 80.3319];
const CAMPUS_ZOOM = 16;

// Building/Location data with real-ish coordinates around CSJMU
const BUILDINGS = [
  {
    id: 'main_gate',
    name: 'Main Gate',
    type: 'gate',
    coords: [26.4462, 80.3338],
    icon: '🚪',
    description: 'Main entrance to CSJMU campus. Security checkpoint.',
    hours: '24/7',
    floors: 0,
    dept: null,
    tags: ['entrance', 'security'],
  },
  {
    id: 'uiet',
    name: 'UIET Building',
    type: 'academic',
    coords: [26.4512, 80.3285],
    icon: '🏗️',
    description: 'University Institute of Engineering & Technology. Houses CSE, ECE, ME, and EE departments.',
    hours: '8:00 AM – 6:00 PM',
    floors: 4,
    dept: 'Engineering & Technology',
    tags: ['engineering', 'labs', 'classrooms'],
    rooms: ['101', '102', '103', '201', '202', '203', '204', '301', '302', '303', '401'],
    hasElevator: true,
    hasRamp: true,
  },
  {
    id: 'library',
    name: 'Central Library',
    type: 'facility',
    coords: [26.4498, 80.3298],
    icon: '📚',
    description: 'Three-storied central library established in 1968. Seating for 700+ users. Houses over 2 lakh books.',
    hours: '9:00 AM – 8:00 PM',
    floors: 3,
    dept: null,
    tags: ['library', 'study', 'books'],
    hasElevator: true,
    hasRamp: true,
  },
  {
    id: 'admin',
    name: 'Admin Block',
    type: 'admin',
    coords: [26.4488, 80.3322],
    icon: '🏛️',
    description: 'Central administrative building. Vice-Chancellor office, Registrar, Finance, and Student Affairs.',
    hours: '9:00 AM – 5:00 PM',
    floors: 3,
    dept: 'Administration',
    tags: ['admin', 'vc', 'registrar'],
    hasElevator: true,
    hasRamp: true,
  },
  {
    id: 'science',
    name: 'Science Faculty',
    type: 'academic',
    coords: [26.4522, 80.3312],
    icon: '🔬',
    description: 'Faculty of Science. Departments of Physics, Chemistry, Mathematics, and Statistics.',
    hours: '8:00 AM – 5:00 PM',
    floors: 3,
    dept: 'Science',
    tags: ['science', 'labs', 'physics', 'chemistry', 'maths'],
    rooms: ['G1', 'G2', '101', '102', '201', '202', '301'],
    hasElevator: false,
    hasRamp: true,
  },
  {
    id: 'arts',
    name: 'Arts Faculty',
    type: 'academic',
    coords: [26.4478, 80.3288],
    icon: '🎨',
    description: 'Faculty of Arts. Departments of English, Hindi, History, Political Science, and Philosophy.',
    hours: '8:00 AM – 5:00 PM',
    floors: 2,
    dept: 'Arts & Humanities',
    tags: ['arts', 'humanities', 'classrooms'],
    rooms: ['A1', 'A2', 'A3', 'A4', 'B1', 'B2', 'B3'],
    hasElevator: false,
    hasRamp: true,
  },
  {
    id: 'commerce',
    name: 'Commerce Faculty',
    type: 'academic',
    coords: [26.4493, 80.3352],
    icon: '💼',
    description: 'Faculty of Commerce. BBA, B.Com, and MBA programs.',
    hours: '8:00 AM – 5:00 PM',
    floors: 2,
    dept: 'Commerce & Business',
    tags: ['commerce', 'bba', 'mba', 'classrooms'],
    rooms: ['C1', 'C2', 'C3', 'C4', 'C5'],
    hasElevator: false,
    hasRamp: false,
  },
  {
    id: 'exam_hall',
    name: 'Examination Hall',
    type: 'facility',
    coords: [26.4507, 80.3332],
    icon: '📝',
    description: 'Main examination centre. Used for semester and annual exams.',
    hours: 'As per exam schedule',
    floors: 2,
    dept: null,
    tags: ['exam', 'hall'],
    rooms: ['Hall A', 'Hall B', 'Hall C', 'Hall D'],
    hasElevator: false,
    hasRamp: true,
  },
  {
    id: 'computer_center',
    name: 'Computer Center',
    type: 'facility',
    coords: [26.4516, 80.3302],
    icon: '💻',
    description: 'Central computing facility. Open labs, Wi-Fi management, and IT support.',
    hours: '9:00 AM – 7:00 PM',
    floors: 2,
    dept: 'IT Services',
    tags: ['computer', 'lab', 'wifi', 'internet'],
    hasElevator: false,
    hasRamp: true,
  },
  {
    id: 'boys_hostel',
    name: 'Boys Hostel',
    type: 'residential',
    coords: [26.4535, 80.3342],
    icon: '🏠',
    description: 'Male student residential quarters. Rooms, common room, mess facility.',
    hours: '24/7',
    floors: 4,
    dept: null,
    tags: ['hostel', 'residential', 'boys'],
    hasElevator: false,
    hasRamp: false,
  },
  {
    id: 'girls_hostel',
    name: 'Girls Hostel',
    type: 'residential',
    coords: [26.4542, 80.3298],
    icon: '🏠',
    description: 'Female student residential quarters. Secured campus with warden.',
    hours: '24/7',
    floors: 3,
    dept: null,
    tags: ['hostel', 'residential', 'girls'],
    hasElevator: false,
    hasRamp: true,
  },
  {
    id: 'sports',
    name: 'Sports Complex',
    type: 'facility',
    coords: [26.4525, 80.3365],
    icon: '🏟️',
    description: 'University sports ground. Cricket, football, basketball courts, and indoor games.',
    hours: '6:00 AM – 7:00 PM',
    floors: 1,
    dept: 'Sports & Physical Education',
    tags: ['sports', 'ground', 'gym'],
    hasElevator: false,
    hasRamp: false,
  },
  {
    id: 'canteen',
    name: 'Central Canteen',
    type: 'amenity',
    coords: [26.4502, 80.3318],
    icon: '🍽️',
    description: 'Main campus food court. Affordable meals, snacks, and beverages.',
    hours: '8:00 AM – 8:00 PM',
    floors: 1,
    dept: null,
    tags: ['food', 'canteen', 'cafeteria'],
    hasElevator: false,
    hasRamp: false,
  },
  {
    id: 'health_center',
    name: 'Health Center',
    type: 'emergency',
    coords: [26.4490, 80.3278],
    icon: '🏥',
    description: 'University health center with first-aid, doctor on call, and ambulance service.',
    hours: '24/7 (Emergency)',
    floors: 1,
    dept: 'Medical',
    tags: ['hospital', 'health', 'medical', 'first-aid'],
    hasElevator: false,
    hasRamp: true,
  },
  {
    id: 'auditorium',
    name: 'University Auditorium',
    type: 'facility',
    coords: [26.4480, 80.3310],
    icon: '🎭',
    description: 'Main auditorium for convocations, seminars, cultural events. Capacity 1500.',
    hours: 'Event-based',
    floors: 2,
    dept: null,
    tags: ['auditorium', 'events', 'cultural'],
    hasElevator: true,
    hasRamp: true,
  },
  {
    id: 'parking',
    name: 'Main Parking',
    type: 'amenity',
    coords: [26.4468, 80.3330],
    icon: '🅿️',
    description: 'Main parking area near the entrance. Two-wheeler and four-wheeler parking.',
    hours: '24/7',
    floors: 0,
    dept: null,
    tags: ['parking', 'vehicles'],
  },
  {
    id: 'shahu_park',
    name: 'Shahu Ji Park',
    type: 'landmark',
    coords: [26.4504, 80.3345],
    icon: '🌳',
    description: 'Beautiful green park in the heart of campus. Walking paths and seating areas.',
    hours: '6:00 AM – 8:00 PM',
    floors: 0,
    dept: null,
    tags: ['park', 'garden', 'relax'],
  },
];

// Amenity points (not buildings — small facilities)
const AMENITIES = [
  { id: 'wc1', type: 'water', name: 'Water Cooler', coords: [26.4500, 80.3305], near: 'library' },
  { id: 'wc2', type: 'water', name: 'Water Cooler', coords: [26.4510, 80.3290], near: 'uiet' },
  { id: 'wc3', type: 'water', name: 'Water Cooler', coords: [26.4520, 80.3315], near: 'science' },
  { id: 'wc4', type: 'water', name: 'Water Cooler', coords: [26.4488, 80.3325], near: 'admin' },
  { id: 'wr1', type: 'washroom', name: 'Washroom (M/F)', coords: [26.4498, 80.3302], near: 'library' },
  { id: 'wr2', type: 'washroom', name: 'Washroom (M/F)', coords: [26.4513, 80.3288], near: 'uiet' },
  { id: 'wr3', type: 'washroom', name: 'Washroom (M/F)', coords: [26.4507, 80.3335], near: 'exam_hall' },
  { id: 'wr4', type: 'washroom', name: 'Washroom (M)', coords: [26.4536, 80.3345], near: 'boys_hostel' },
  { id: 'wr5', type: 'washroom', name: 'Washroom (F)', coords: [26.4543, 80.3300], near: 'girls_hostel' },
  { id: 'atm1', type: 'atm', name: 'SBI ATM', coords: [26.4470, 80.3335], near: 'main_gate' },
  { id: 'atm2', type: 'atm', name: 'PNB ATM', coords: [26.4503, 80.3320], near: 'canteen' },
  { id: 'ch1', type: 'charging', name: 'Charging Point', coords: [26.4500, 80.3300], near: 'library' },
  { id: 'ch2', type: 'charging', name: 'Charging Point', coords: [26.4514, 80.3288], near: 'uiet' },
  { id: 'pc1', type: 'photocopy', name: 'Photocopy Shop', coords: [26.4496, 80.3310], near: 'library' },
  { id: 'pc2', type: 'photocopy', name: 'Photocopy & Print', coords: [26.4508, 80.3292], near: 'uiet' },
  { id: 'sec1', type: 'security', name: 'Security Post', coords: [26.4463, 80.3340], near: 'main_gate' },
  { id: 'sec2', type: 'security', name: 'Security Booth', coords: [26.4530, 80.3340], near: 'boys_hostel' },
  { id: 'fe1', type: 'fire_exit', name: 'Fire Assembly Point', coords: [26.4495, 80.3315], near: 'admin' },
];

// Amenity type metadata
const AMENITY_TYPES = {
  water:     { icon: '🚰', label: 'Water Cooler', color: '#4FC3F7' },
  washroom:  { icon: '🚻', label: 'Washroom', color: '#AB47BC' },
  atm:       { icon: '🏧', label: 'ATM', color: '#66BB6A' },
  charging:  { icon: '🔌', label: 'Charging', color: '#FFA726' },
  photocopy: { icon: '🖨️', label: 'Print/Copy', color: '#78909C' },
  security:  { icon: '🛡️', label: 'Security', color: '#EF5350' },
  fire_exit: { icon: '🧯', label: 'Fire Point', color: '#FF7043' },
};

// Simulated timetable data
const TIMETABLE = [
  {
    time: '09:00',
    endTime: '10:00',
    subject: 'Operating Systems Lab',
    room: 'Room 204',
    building: 'uiet',
    type: 'lab',
  },
  {
    time: '10:15',
    endTime: '11:15',
    subject: 'Data Structures',
    room: 'Room 102',
    building: 'uiet',
    type: 'lecture',
  },
  {
    time: '11:30',
    endTime: '12:30',
    subject: 'Mathematics-III',
    room: 'Room 201',
    building: 'science',
    type: 'lecture',
  },
  {
    time: '14:00',
    endTime: '15:00',
    subject: 'DBMS',
    room: 'Room 301',
    building: 'uiet',
    type: 'lecture',
  },
  {
    time: '15:15',
    endTime: '16:15',
    subject: 'Library Study Session',
    room: 'Reading Hall',
    building: 'library',
    type: 'self-study',
  },
];

// Emergency contacts
const EMERGENCY_CONTACTS = [
  { type: 'medical', label: 'Health Center', phone: '0512-XXXXXXX', building: 'health_center' },
  { type: 'security', label: 'Campus Security', phone: '0512-XXXXXXX', building: 'main_gate' },
  { type: 'fire', label: 'Fire Station', phone: '101', building: null },
  { type: 'police', label: 'Police', phone: '100', building: null },
  { type: 'ambulance', label: 'Ambulance', phone: '108', building: null },
  { type: 'women', label: 'Women Helpline', phone: '1091', building: null },
];

// Simulated chat responses
const CHAT_RESPONSES = {
  'where is uiet': { text: 'UIET Building is located in the northern part of campus, near the Science Faculty. It houses CSE, ECE, ME, and EE departments.', building: 'uiet' },
  'nearest washroom': { text: 'The nearest washroom is 80m from your location, near the Central Library.', amenity: 'wr1' },
  'nearest water': { text: 'There\'s a water cooler 45m away, near the Library entrance.', amenity: 'wc1' },
  'library timings': { text: 'The Central Library is open from 9:00 AM to 8:00 PM on weekdays, and 9:00 AM to 5:00 PM on weekends.', building: 'library' },
  'my next class': { text: 'Your next class is Operating Systems Lab at 09:00 AM in UIET Room 204.', building: 'uiet' },
  'exam hall': { text: 'The Examination Hall is located east of the Admin Block, near Shahu Ji Park.', building: 'exam_hall' },
  'canteen': { text: 'The Central Canteen is in the heart of campus, open 8 AM – 8 PM. Known for affordable meals!', building: 'canteen' },
  'parking': { text: 'Main parking is near the Main Gate entrance. Both two-wheeler and four-wheeler parking available.', building: 'parking' },
  'health center': { text: 'The Health Center is west of the Library. Has a doctor on call 24/7 for emergencies.', building: 'health_center' },
  'default': { text: 'I can help you find locations, nearby amenities, and navigate across campus. Try asking "Where is UIET?" or "Nearest washroom".' },
};

// Navigation route presets (for demo)
const DEMO_ROUTES = {
  gate_to_uiet: {
    from: 'main_gate',
    to: 'uiet',
    distance: '850m',
    walkTime: '11 min',
    cycleTime: '4 min',
    steps: [
      { instruction: 'Exit Main Gate, walk north on Campus Road', distance: '200m' },
      { instruction: 'Continue past Admin Block on your left', distance: '150m' },
      { instruction: 'Turn left at the Central Canteen', distance: '100m' },
      { instruction: 'Continue straight past the Library', distance: '200m' },
      { instruction: 'UIET Building is ahead on your right', distance: '200m' },
    ],
    path: [
      [26.4462, 80.3338], // Main Gate
      [26.4470, 80.3335],
      [26.4478, 80.3330],
      [26.4488, 80.3322], // Admin Block
      [26.4495, 80.3318],
      [26.4502, 80.3318], // Canteen
      [26.4502, 80.3310],
      [26.4498, 80.3298], // Library
      [26.4505, 80.3290],
      [26.4512, 80.3285], // UIET
    ],
  },
  gate_to_library: {
    from: 'main_gate',
    to: 'library',
    distance: '550m',
    walkTime: '7 min',
    cycleTime: '3 min',
    steps: [
      { instruction: 'Exit Main Gate, walk north on Campus Road', distance: '200m' },
      { instruction: 'Continue past Admin Block on your left', distance: '150m' },
      { instruction: 'Turn left after the Canteen', distance: '100m' },
      { instruction: 'Central Library is ahead', distance: '100m' },
    ],
    path: [
      [26.4462, 80.3338],
      [26.4470, 80.3335],
      [26.4478, 80.3330],
      [26.4488, 80.3322],
      [26.4495, 80.3318],
      [26.4502, 80.3318],
      [26.4502, 80.3310],
      [26.4498, 80.3298],
    ],
  },
  library_to_exam: {
    from: 'library',
    to: 'exam_hall',
    distance: '380m',
    walkTime: '5 min',
    cycleTime: '2 min',
    steps: [
      { instruction: 'Exit Library, walk east', distance: '100m' },
      { instruction: 'Turn right at the junction', distance: '130m' },
      { instruction: 'Continue toward Shahu Ji Park', distance: '100m' },
      { instruction: 'Examination Hall on your left', distance: '50m' },
    ],
    path: [
      [26.4498, 80.3298],
      [26.4500, 80.3308],
      [26.4502, 80.3318],
      [26.4505, 80.3325],
      [26.4507, 80.3332],
    ],
  },
};

// Reviews data for buildings
const REVIEWS = {
  uiet: [
    { user: 'Rahul K.', userId: 'COS2024051', rating: 4, text: 'Great labs, especially the new computer lab on 3rd floor. WiFi could be better.', time: '2 days ago' },
    { user: 'Priya S.', userId: 'COS2024089', rating: 5, text: 'Best department building on campus. Clean washrooms and good canteen nearby.', time: '1 week ago' },
    { user: 'Amit V.', userId: 'COS2023112', rating: 3, text: 'Elevator is often broken. Stairs can be tough with heavy bags.', time: '2 weeks ago' },
  ],
  library: [
    { user: 'Sneha M.', userId: 'COS2024023', rating: 5, text: 'Excellent collection. The reading hall is very peaceful for exam prep.', time: '3 days ago' },
    { user: 'Vikram R.', userId: 'COS2023067', rating: 4, text: 'Good resources but gets very crowded during exam season.', time: '1 week ago' },
  ],
  canteen: [
    { user: 'Deepak G.', userId: 'COS2024015', rating: 4, text: 'Samosas are legendary! Long queue at lunch though.', time: '1 day ago' },
    { user: 'Ananya P.', userId: 'COS2024078', rating: 3, text: 'Decent food at affordable prices. Could use more seating.', time: '5 days ago' },
  ],
};

export {
  CAMPUS_CENTER, CAMPUS_ZOOM, BUILDINGS, AMENITIES, AMENITY_TYPES,
  TIMETABLE, EMERGENCY_CONTACTS, CHAT_RESPONSES, DEMO_ROUTES, REVIEWS
};
